
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x600")
window.configure(bg = "#FFFFFF")






canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    578.0,
    9.0,
    578.0,
    590.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    26.0,
    105.0,
    551.0,
    560.0,
    fill="#000000",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("assets/start_btn.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=814.26953125,
    y=150.22438049316406,
    width=77.3873291015625,
    height=29.76434326171875
)

button_image_2 = PhotoImage(
    file=relative_to_assets("assets/stop_btn.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=902.0,
    y=152.0,
    width=77.3873291015625,
    height=29.76434326171875
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("assets/entry_1.png"))
entry_bg_1 = canvas.create_image(
    804.0,
    415.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#E7E7E7",
    highlightthickness=0
)
entry_1.place(
    x=617.0,
    y=270.0,
    width=374.0,
    height=288.0
)

canvas.create_text(
    620.0,
    242.0,
    anchor="nw",
    text="translated words :",
    fill="#000000",
    font=("Roboto", 18 * -1)
)

canvas.create_text(
    702.0,
    40.0,
    anchor="nw",
    text="Isign",
    fill="#000000",
    font=("Roboto", 64 * -1)
)

canvas.create_rectangle(
    26.0,
    43.0,
    46.0,
    44.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    621.0,
    128.0,
    804.0,
    300.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
